### Registrar Usuario (Exitoso)
POST {{baseUrl}}/users
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "email": "mrx@gmail.com",
  "password": "superSecretPassword"
}

### Registrar Usuario (Fallo - password corto)
POST {{baseUrl}}/users
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "email": "mrx@gmail.com",
  "password": "123"
}

### Iniciar Sesión (Exitoso)
POST {{baseUrl}}/users/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "email": "mrx@gmail.com",
  "password": "superSecretPassword"
}

### Iniciar Sesión (Fallo - password incorrecto)
POST {{baseUrl}}/users/login
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "email": "mrx@gmail.com",
  "password": "wrongPassword"
}
